apiVersion: 1

datasources:
  - name: InfluxDB - Fairbanks Climate
    uid: fairbanks-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: $__env{INFLUXDB_ORG}
      defaultBucket: $__env{INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
