services:
  spark-master:
    image: apache/spark:3.5.9-python3
    container_name: spark-master
    hostname: spark-master
    restart: on-failure
    entrypoint: []
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"
    ports:
      - "8080:8080"   # Spark master web UI
      - "7077:7077"   # Spark master RPC
    volumes:
      - ./data:/opt/spark-data
      - ./scripts:/opt/spark-apps
      - ./conf:/opt/spark/conf
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:3.5.9-python3
    container_name: spark-worker-1
    hostname: spark-worker-1
    restart: on-failure
    entrypoint: []
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - "2g"
      - --webui-port
      - "8081"
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
      - ./scripts:/opt/spark-apps
      - ./conf:/opt/spark/conf
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark:3.5.9-python3
    container_name: spark-worker-2
    hostname: spark-worker-2
    restart: on-failure
    entrypoint: []
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - "2g"
      - --webui-port
      - "8081"
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
      - ./scripts:/opt/spark-apps
      - ./conf:/opt/spark/conf
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
    networks:
      - spark-net

  spark-history:
    image: apache/spark:3.5.9-python3
    container_name: spark-history
    hostname: spark-history
    restart: on-failure
    entrypoint: []
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.history.HistoryServer
    ports:
      - "18080:18080"   # Spark History Server UI
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
      - ./conf:/opt/spark/conf
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
